#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: kirycreEP'S EPIC COOL PAGE !!!!!!!!!

# Short bio or description (displayed in the header)
description: help

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /pain.png
